spring.application.name=Gestion_De_Inventario

server.port=8081

# conexion
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_inventario?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql

# hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Nombre del pool
spring.datasource.hikari.pool-name=InventarioPool

# Máximo de conexiones que puede tener el pool
spring.datasource.hikari.maximum-pool-size=10

# Mínimo de conexiones libres que Hikari intentará mantener
spring.datasource.hikari.minimum-idle=2

# Tiempo máximo esperando una conexión libre
# 5000 ms = 5 segundos
spring.datasource.hikari.connection-timeout=5000

# Tiempo máximo que una conexión SOBRANTE puede estar sin usarse
# 600000 ms = 10 minutos
spring.datasource.hikari.idle-timeout=600000

# Tiempo máximo de vida de una conexión
# 1800000 ms = 30 minutos
spring.datasource.hikari.max-lifetime=1800000

# Tiempo máximo para comprobar si una conexión sigue siendo válida
# 3000 ms = 3 segundos
spring.datasource.hikari.validation-timeout=3000