spring.application.name=gestion-inventario

# ==========================================
# MYSQL
# ==========================================

spring.datasource.url=jdbc:mysql://2.25.105.230:3306/gestion_inventario
spring.datasource.username=inventario_user
spring.datasource.password=VZMNPB2eyvu9jfJDQEn84Siwsm7A6HcaY5I03UbGTCFKzrWOl1ktxoLhdRXqpg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# HIKARICP - CONNECTION POOL
# ==========================================

# Asegurar que Spring use Hikari
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

spring.datasource.hikari.pool-name=InventarioPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.validation-timeout=3000

# ==========================================
# LOGGING PARA VERIFICAR HIKARI
# ==========================================
logging.level.com.zaxxer.hikari.HikariConfig=INFO
logging.level.com.zaxxer.hikari=INFO

# ==========================================
# JWT
# ==========================================
jwt.secret=KnBQJP4TmB7V54aF8MoAs5B5LsnjyV8AGRvLPBJBG+rHHePgoD27gugW4fxk4QyiZ8faCZ+33lub+ugMMgeIlQ
jwt.expiration=3600000
jwt.issuer=gestion-inventario-api
jwt.audience=gestion-inventario-client
cors.allowed-origin=http://localhost:4200
